source:      .
destination: ./_site
exclude:
  - venv
  - deploy
  - stage
  - csv2json
  - package
  - pullandpackage
  - readme.md
  - lots.py
  - Gemfile
  - Gemfile.lock
  - flat-rate-desktop-marker.psd
  - sprites.psd
  - marker-sprites.psd
  - marker-sprites-tiny.psd
lot_dir: lots
lot_data: js/lots-data.js
dest_dir: destinations
dest_data: js/destinations.js
epark_intro: e-Park garages track and display real-time parking space availability, helping you find parking faster.
epark_footer_links:
  -
    text: City of Seattle e-Park
    href: http://www.seattle.gov/transportation/epark/mobile/
3dollar_intro: Spots in many garages in the Central Waterfront and Pioneer Square start as low as $3/hour.
flat_intro: Some parking garages and lots offer a flat evening and weekend rate of $7 or less. Please check with garage for hours and details.
